// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LihatChatTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lihatChat() {
    driver.get("https://shopee.co.id/");
    driver.manage().window().setSize(new Dimension(1382, 824));
    js.executeScript("window.scrollTo(0,140)");
    driver.findElement(By.cssSelector(".src-components-MainLayout-index__logo--1byC8 > .chat-icon")).click();
    driver.findElement(By.cssSelector(".src-components-ConversationListsLayout-Headerbar-index__selected--3FjOw")).click();
    driver.findElement(By.cssSelector(".src-components-Common-Menus-index__option--2lyP0:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".src-components-ConversationListsLayout-Headerbar-index__input--10eES")).click();
    js.executeScript("window.scrollTo(0,439.20001220703125)");
    driver.findElement(By.cssSelector(".src-components-ConversationListsLayout-Headerbar-index__input--10eES")).sendKeys("swo");
    driver.findElement(By.cssSelector(".src-components-ConversationListsLayout-ConversationCells-index__username--SOXgT > div > div")).click();
    js.executeScript("window.scrollTo(0,439.20001220703125)");
    js.executeScript("window.scrollTo(0,439.20001220703125)");
  }
}
